### ISSUE TITLE
Wrong Newtonsoft.JSON assembly reference.

### ISSUE THREAD

**Issue by korifeich** [omise/omise-dotnet#16]
HI!

I've added your SDK to my project using NuGet package manager. It tells that it requires Newtonsoft.JSON version 6.0.5 but whe I try to use your SDK libs I get error message:
Newtonsoft.JSON version 8.0.0 was not found.

I've downloaded your repository and saw that you are actually using Newtonsoft.JSON version 8.0.2, so I had to rewrite my we.config file to point 8.0.0 dll to my project 7.0.1 version.

can you please update your package or sources to contain right Newtonsoft.JSON assembly version, or lower version in your dll.

Best Regards
Konstantin.

**Comment by chakrit** [comment]
@korifeich thanks for reporting this issue!

It seems `xbuild` and `nuget` did not honor/check the `nuspec` file so I did not notice about this before.

**Comment by chakrit** [comment]
Fixed in [v2.0.3.31131](https://www.nuget.org/packages/Omise/2.0.3.31131)
