### ISSUE TITLE
Wrong cutomer string Hangs request.

### ISSUE THREAD

**Issue by korifeich** [omise/omise-dotnet#17]
HI!

When I specify wong customer ID ( let it be email address) in CreateChargeRequest, charge request hangs and nothing happens. Here is a code sample from your example that shows 

```
public class CreateChargeExample : Example {
        public async override Task Run() {
            var token = await CreateToken();
            try
            {
                var charge = await Client.Charges.Create(new CreateChargeRequest
                {
                    Amount = int.Parse(Prompt("how much you want to charge")),
                    Currency = "usd",
                    Card = token.Id,
                    Customer = "admin@yourstore.com"
                });
                Print("created charge: " + charge.Id);
            }
            catch(Exception ex)
            {
                Console.ReadKey();
            }

        }
    }
```

**Comment by chakrit** [comment]
@korifeich you are absorbing all exceptions `catch (Exception ex)` and waiting for a keypress when that happens (`Console.ReadKey()`) can you remove the `try/catch` block and give me the actual exception?

**Comment by korifeich** [comment]
Oh,

Sorry it was an error in my production code everything works fine, it returns: customer admin@yourstore.com was not found

**Comment by chakrit** [comment]
@korifeich great to hear! : ) i'm closing this issue then.
