### ISSUE TITLE
Omise HTTP Request workint at Devt IIS Express but not working when deployed to IIS

### ISSUE THREAD

**Issue by XCoder123x** [omise/omise-dotnet#42]
my app is 100% smooth and running when run using Visual Studio and IIS express. HTTP Request error Omise not working when it is already deployed in IIS.

Please help. Thanks

**Comment by rezigned** [comment]
Hi @XCoder123x.

Thanks for reporting the issue. Could you provide more information such as

* Windows Version and Patch
* IIS version
* TLS supported? 1.2
* .NET Framework version
* omise-dotnet version

Also, please note that when using `omise-dotnet` you might refer to this list to check the compatibility of .NET Standard versions https://docs.microsoft.com/en-us/dotnet/standard/net-standard (we use `.NET Standard 2.0`)

**Comment by rezigned** [comment]
It turned out to be IP whitelisting issues on client-side. Hence, I'll close this.

**Comment by XCoder123x** [comment]
Yeah, issue resolved. Thanks
