### ISSUE TITLE
Retrieve a source does not include 

### ISSUE THREAD

**Issue by TaiAreerob** [omise/omise-dotnet#57]
I have tried to retrieve source using the library, but it seems like it does not include in the library.

**Comment by FhanOmise** [comment]
Hi @TaiAreerob, Can you create a Source using below example?

```c#
var client = new Omise.Client(skey: "your_skey");

var source = await client.Sources.Create(new Omise.Models.CreatePaymentSourceRequest
{
    Amount = 1000,
    Currency = "THB",
    Type = Omise.Models.OffsiteTypes.InternetBankingSCB
});
```

Could you please provide a clarification of what doesn't work?

**Comment by aashishgurung** [comment]
We’re going to close this since there hasn’t been any activity for a while. If this issue is still relevant, please feel free to reopen it with more details and we’ll take another look.
